version: '3.8'

services:
  nginx:
    container_name: seln_nginx_dev-container
    image: nginx
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./:/app
    links:
      - php-fpm
    ports:
      - ${NGINX_PORT}

  php-fpm:
    container_name: seln_php-fpm-container
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - ${APP_PORT}
    volumes:
      - ./:/app
    working_dir: /app

  php-cli:
    container_name: seln_php-cli-container
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./:/app

  api-postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}